# Generated by Django 5.2.5 on 2025-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Verified'), (3, 'Rejected')], default=1),
        ),
    ]
